annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - '`nodes/proxy` permission was removed from default clusterrole. This permission may be used to [raise privileges](https://grahamhelton.com/blog/nodes-proxy-rce). In case the vmagent will be used to scrape Kubelet''s proxy endpoint, it is recommended to create a custom role with the necessary permissions.'
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-logs-single
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victorialogs/
    - name: Changelog
      url: https://docs.victoriametrics.com/victorialogs/changelog/
  artifacthub.io/readme: |
    # VictoriaLogs Single Helm chart

    Chart documentation is available [here](https://docs.victoriametrics.com/helm/victoria-logs-single/)
apiVersion: v2
appVersion: v1.44.0
dependencies:
- condition: vector.enabled
  name: vector
  repository: https://helm.vector.dev
  version: 0.46.*
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts/
  version: 0.0.*
description: The VictoriaLogs single Helm chart deploys VictoriaLogs database in Kubernetes.
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- victorialogs
- logs
- kubernetes
- observability
- logsql
kubeVersion: '>=1.25.0-0'
name: victoria-logs-single
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.11.25
