apiVersion: v2
appVersion: v2.0.6
description: SpeedTest by OpenSpeedTest
home: https://openspeedtest.com/
icon: https://raw.githubusercontent.com/openspeedtest/Speed-Test/main/assets/images/icons/android-chrome-512x512.png
keywords:
- speedtest
- speed test
- openspeedtest
maintainers:
- email: support@openspeedtest.com
  name: OpenSpeedTest™️
name: openspeedtest
sources:
- https://github.com/openspeedtest/Helm-chart
type: application
version: 2.0.6
