apiVersion: v2
name: onedev
version: 11.9.0
description: All-In-One DevOps Platform
type: application
keywords:
  - onedev
  - devops
  - vcs
  - cicd
home: https://onedev.io
maintainers:
  - name: Robin Shen
    email:  robin@onedev.io
  - name: Abdul Khaliq
    email: a.khaliq@outlook.my
appVersion: 11.9.0
