annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - bump vlagent version to [v1.45.0](https://github.com/VictoriaMetrics/VictoriaLogs/releases/tag/v1.45.0).
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-logs-agent
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Changelog
      url: https://docs.victoriametrics.com/changelog/
  artifacthub.io/readme: |
    # VictoriaLogs Agent Helm chart

    Chart documentation is available [here](https://docs.victoriametrics.com/helm/victoria-logs-agent/)
apiVersion: v2
appVersion: v1.45.0
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
description: VictoriaLogs Agent - accepts logs from various protocols and replicates
  them across multiple VictoriaLogs instances.
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victorialogs
- logs
- agent
- collector
- kubernetes
- observability
kubeVersion: '>=1.25.0-0'
name: victoria-logs-agent
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.0.10
