{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: lobe-chat
  labels:
    app.kubernetes.io/name: {{ include "lobe-chat.name" . }}
    helm.sh/chart: {{ include "lobe-chat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $val := .Values.secret.env }}
  {{- if eq $key "KEY_VAULTS_SECRET" }}
  {{- if eq $val "" }}
  {{ $key }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- else }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
