apiVersion: v2
appVersion: 1.23.17
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 23.2.2
description: A self-hosted Monitoring tool like "Uptime-Robot".
home: https://github.com/dirsigler/uptime-kuma-helm
icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
maintainers:
- email: dennis@irsigler.dev
  name: dirsigler
name: uptime-kuma
sources:
- https://github.com/louislam/uptime-kuma
type: application
version: 2.24.0
