apiVersion: v2
appVersion: "260601"
description: A Photoprism Helm chart for Kubernetes
home: https://photoprism.org/
name: photoprism
sources:
- https://github.com/photoprism/photoprism
version: 1.4.4
